low_level_features = ['lowlevel.average_loudness', 'lowlevel.barkbands_crest.dmean', 'lowlevel.barkbands_crest.mean',
'lowlevel.barkbands_crest.stdev', 'lowlevel.barkbands_flatness_db.dmean', 'lowlevel.barkbands_flatness_db.mean',
'lowlevel.barkbands_flatness_db.stdev', 'lowlevel.barkbands_kurtosis.dmean', 'lowlevel.barkbands_kurtosis.mean',
'lowlevel.barkbands_kurtosis.stdev', 'lowlevel.barkbands_skewness.dmean', 'lowlevel.barkbands_skewness.mean',
'lowlevel.barkbands_skewness.stdev', 'lowlevel.barkbands_spread.dmean', 'lowlevel.barkbands_spread.mean',
'lowlevel.barkbands_spread.stdev', 'lowlevel.dissonance.dmean', 'lowlevel.dissonance.mean', 'lowlevel.dissonance.stdev',
'lowlevel.dynamic_complexity', 'lowlevel.erbbands_crest.dmean', 'lowlevel.erbbands_crest.mean',
'lowlevel.erbbands_crest.stdev', 'lowlevel.erbbands_flatness_db.dmean', 'lowlevel.erbbands_flatness_db.mean',
'lowlevel.erbbands_flatness_db.stdev', 'lowlevel.erbbands_kurtosis.dmean', 'lowlevel.erbbands_kurtosis.mean', 'lowlevel.erbbands_kurtosis.stdev',
'lowlevel.erbbands_skewness.dmean', 'lowlevel.erbbands_skewness.mean', 'lowlevel.erbbands_skewness.stdev',
'lowlevel.erbbands_spread.dmean', 'lowlevel.erbbands_spread.mean', 'lowlevel.erbbands_spread.stdev', 'lowlevel.hfc.dmean',
'lowlevel.hfc.mean', 'lowlevel.hfc.stdev', 'lowlevel.loudness_ebu128.integrated', 'lowlevel.loudness_ebu128.loudness_range',
'lowlevel.loudness_ebu128.momentary.dmean', 'lowlevel.loudness_ebu128.momentary.mean', 'lowlevel.loudness_ebu128.momentary.stdev',
'lowlevel.loudness_ebu128.short_term.dmean', 'lowlevel.loudness_ebu128.short_term.mean', 'lowlevel.loudness_ebu128.short_term.stdev',
'lowlevel.melbands_crest.dmean', 'lowlevel.melbands_crest.mean', 'lowlevel.melbands_crest.stdev', 'lowlevel.melbands_flatness_db.dmean',
'lowlevel.melbands_flatness_db.mean', 'lowlevel.melbands_flatness_db.stdev', 'lowlevel.melbands_kurtosis.dmean',
'lowlevel.melbands_kurtosis.mean', 'lowlevel.melbands_kurtosis.stdev', 'lowlevel.melbands_skewness.dmean',
'lowlevel.melbands_skewness.mean', 'lowlevel.melbands_skewness.stdev', 'lowlevel.melbands_spread.dmean', 'lowlevel.melbands_spread.mean',
'lowlevel.melbands_spread.stdev', 'lowlevel.pitch_salience.dmean', 'lowlevel.pitch_salience.mean', 'lowlevel.pitch_salience.stdev',
'lowlevel.silence_rate_20dB.dmean', 'lowlevel.silence_rate_20dB.mean', 'lowlevel.silence_rate_20dB.stdev',
'lowlevel.silence_rate_30dB.dmean', 'lowlevel.silence_rate_30dB.mean', 'lowlevel.silence_rate_30dB.stdev',
'lowlevel.silence_rate_60dB.dmean', 'lowlevel.silence_rate_60dB.mean', 'lowlevel.silence_rate_60dB.stdev',
'lowlevel.spectral_centroid.dmean', 'lowlevel.spectral_centroid.mean', 'lowlevel.spectral_centroid.stdev',
'lowlevel.spectral_complexity.dmean', 'lowlevel.spectral_complexity.mean', 'lowlevel.spectral_complexity.stdev',
'lowlevel.spectral_decrease.dmean', 'lowlevel.spectral_decrease.mean', 'lowlevel.spectral_decrease.stdev',
'lowlevel.spectral_energy.dmean', 'lowlevel.spectral_energy.mean', 'lowlevel.spectral_energy.stdev',
'lowlevel.spectral_energyband_high.dmean', 'lowlevel.spectral_energyband_high.mean', 'lowlevel.spectral_energyband_high.stdev',
'lowlevel.spectral_energyband_low.dmean', 'lowlevel.spectral_energyband_low.mean', 'lowlevel.spectral_energyband_low.stdev',
'lowlevel.spectral_energyband_middle_high.dmean', 'lowlevel.spectral_energyband_middle_high.mean',
'lowlevel.spectral_energyband_middle_high.stdev', 'lowlevel.spectral_energyband_middle_low.dmean',
'lowlevel.spectral_energyband_middle_low.mean', 'lowlevel.spectral_energyband_middle_low.stdev', 'lowlevel.spectral_entropy.dmean',
'lowlevel.spectral_entropy.mean', 'lowlevel.spectral_entropy.stdev', 'lowlevel.spectral_flux.dmean', 'lowlevel.spectral_flux.mean',
'lowlevel.spectral_flux.stdev', 'lowlevel.spectral_kurtosis.dmean', 'lowlevel.spectral_kurtosis.mean',
'lowlevel.spectral_kurtosis.stdev', 'lowlevel.spectral_rms.dmean', 'lowlevel.spectral_rms.mean', 'lowlevel.spectral_rms.stdev',
'lowlevel.spectral_rolloff.dmean', 'lowlevel.spectral_rolloff.mean', 'lowlevel.spectral_rolloff.stdev',
'lowlevel.spectral_skewness.dmean', 'lowlevel.spectral_skewness.mean', 'lowlevel.spectral_skewness.stdev',
'lowlevel.spectral_spread.dmean', 'lowlevel.spectral_spread.mean', 'lowlevel.spectral_spread.stdev', 'lowlevel.spectral_strongpeak.dmean',
'lowlevel.spectral_strongpeak.mean', 'lowlevel.spectral_strongpeak.stdev', 'lowlevel.zerocrossingrate.dmean',
'lowlevel.zerocrossingrate.mean', 'lowlevel.zerocrossingrate.stdev', 'metadata.audio_properties.replay_gain',
'rhythm.beats_loudness.dmean', 'rhythm.beats_loudness.mean', 'rhythm.beats_loudness.stdev', 'rhythm.bpm',
'rhythm.bpm_histogram_first_peak_weight', 'rhythm.bpm_histogram_second_peak_spread', 'rhythm.bpm_histogram_second_peak_weight',
'rhythm.danceability', 'rhythm.onset_rate', 'tonal.chords_changes_rate', 'tonal.chords_strength.dmean',
'tonal.chords_strength.mean', 'tonal.chords_strength.stdev', 'tonal.hpcp_crest.dmean', 'tonal.hpcp_crest.mean',
'tonal.hpcp_crest.stdev', 'tonal.hpcp_entropy.dmean', 'tonal.hpcp_entropy.mean', 'tonal.hpcp_entropy.stdev', 'tonal.key_edma.strength',
'tonal.key_krumhansl.strength', 'tonal.key_temperley.strength', 'tonal.tuning_diatonic_strength',
'tonal.tuning_equal_tempered_deviation', 'tonal.tuning_frequency', 'tonal.tuning_nontempered_energy_ratio',
'lowlevel.barkbands.dmean', 'lowlevel.barkbands.mean', 'lowlevel.barkbands.stdev', 'lowlevel.erbbands.dmean',
'lowlevel.erbbands.mean', 'lowlevel.erbbands.stdev', 'lowlevel.gfcc.mean', 'lowlevel.melbands.dmean', 'lowlevel.melbands.mean',
'lowlevel.melbands.stdev', 'lowlevel.melbands128.dmean', 'lowlevel.melbands128.mean', 'lowlevel.melbands128.stdev',
'lowlevel.mfcc.mean', 'lowlevel.spectral_contrast_coeffs.dmean', 'lowlevel.spectral_contrast_coeffs.mean',
'lowlevel.spectral_contrast_coeffs.stdev', 'lowlevel.spectral_contrast_valleys.dmean', 'lowlevel.spectral_contrast_valleys.mean',
'lowlevel.spectral_contrast_valleys.stdev', 'rhythm.beats_loudness_band_ratio.dmean', 'rhythm.beats_loudness_band_ratio.mean',
'rhythm.beats_loudness_band_ratio.stdev', 'tonal.hpcp.dmean', 'tonal.hpcp.mean', 'tonal.hpcp.stdev',
'tonal.thpcp', 'tonal.chords_scale','tonal.key_edma.scale', 'tonal.key_krumhansl.scale']

high_level_features = ["Valence", "Energy", "Anger", "Anxiety", "Excitement", "Happiness", "Relaxation", "Calmness",
                       "Sadness", "Darkness", "Vocalness", "Acousticness", "Depth"]

mood_features = ["Angry", "Anxious", "Excited", "Happy", "Relaxed", "Calm", "Sad", "Dark"]
